### ISSUE TITLE
Accesibility issue for the App AWS ver.

### ISSUE THREAD

**Issue by hagikent** [AllenNeuralDynamics/foraging-behavior-browser#65]
@yosefmaru

I'm using FireFox and Chrome from my Allen-issued MBP (OS12.6.1) and encounter the followings:
1. when accessing the previous address
<img width="358" alt="Screen Shot 2024-04-14 at 18 23 29" src="https://github.com/AllenNeuralDynamics/foraging-behavior-browser/assets/54397345/2d5732fa-c8b8-4286-bce2-fc1179583dbd">

2. when proceeding to the "allenneuraldynamics-test" addredd
in FF
<img width="459" alt="Screen Shot 2024-04-14 at 18 24 45" src="https://github.com/AllenNeuralDynamics/foraging-behavior-browser/assets/54397345/3b72c08c-ac51-44c0-8dea-c2f1a80be7a7">

in Chrome
<img width="477" alt="Screen Shot 2024-04-14 at 18 24 17" src="https://github.com/AllenNeuralDynamics/foraging-behavior-browser/assets/54397345/12112eff-8925-4ee0-b3d8-5623335ac28c">

3. and I need to enter my passwords 3 or 4 times everytime I attempt to use the app.
@hanhou told me he can just cancel this process and it works for him, but if I do that, I encounter handshake error.
<img width="795" alt="Screen Shot 2024-04-14 at 18 25 28" src="https://github.com/AllenNeuralDynamics/foraging-behavior-browser/assets/54397345/baeb4a8d-c020-44ab-b91b-f0631187d453">

____
Anything to be tested? Recommended browser settings(although I use pretty much in default settings) etc? Thanks.

**Comment by hanhou** [comment]
Can you try: 
1. clear the cache of your browser
2. use Incognito mode of Chrome

**Comment by yosefmaru** [comment]
@hagikent
I wasn't able to replicate the error you're seeing. However, I can confidently say that the URL shouldn't require any browser configuration. Let me know if you see the issue when using an incognito browser.
