### ISSUE TITLE
bug: wrong label of virus to intended NM recorded

### ISSUE THREAD

**Issue by rachelstephlee** [AllenNeuralDynamics/foraging-behavior-browser#92]
I used a crude function to determine which NM was being recorded from the virus listed. 

`pAAV.CAG.Flex.NES-JRGECO1a.WPRE.SV40` should be a GcAMP6f virus, not a virus targeting NE. The code only checks if there is NE/NA in the virus name. This should be changed to check if there's GRAB*NE/NA or NE/NA*GRAB instead.

**Comment by rachelstephlee** [comment]
Jeremiah has helped provide some of the virus mapping to NM. This will not be included in the NWB, but the dictionary will be used after the fact for the querying method (streamlit in this case) to interpret the virus used for the NM recorded. 


With that same virus.csv, Rachel will pass along any buggy/wrong virus tags (eg. virus called "NA," virus called "TBA", virus that are the virus lot number and NOT the actual virus itself) to @hagikent and we will fix them.

**Comment by alexpiet** [comment]
@rachelstephlee Can the dictionary that maps virus to NM also be included in the data-utils repo?

**Comment by rachelstephlee** [comment]
@alexpiet  how do you want me to include it -- right now it's a CSV file... it would presumably need to be updated as we use MORE viruses.

**Comment by alexpiet** [comment]
maybe save the csv file in the repo, and then make a function that takes in the NWB file, and returns a dictionary whose keys are `G_1`, `G_2`, `R_1`, `R_2`, and values with the NM name. That way we can easily update the csv file as needed

**Comment by hagikent** [comment]
I sort of like @alexpiet 's suggestion, at least no objections.
@rachelstephlee 
the number of AAVs to be used will be growing but not like 1k; I presume max. ~50 that is totally trackable.

**Comment by rachelstephlee** [comment]
@saskiad proposes that we put the 'intention' of where we're recording and what we're recording, it should be placed in the data description. 

We need to figure out when to put this in. We will do this post-hoc for now. We could use an LLM to generate out a data description (Saskia has an RA who is working with LLMs). 

This will be separate from the 'intended area' that we will include in the surgery request form. 


Our priority list for metadata: 
1. intended recording structure
2. correct probe information 
3. add this 'data description' to address the correct interpretation for virus information

**Comment by hagikent** [comment]
[current look-up table ](https://docs.google.com/spreadsheets/d/1BSdOJpctQ9MV4WBepdd00BDepr7lqV7mxehm6-Z4CrU/edit?usp=sharing) (not yet official, beta, but useful)

**Comment by hagikent** [comment]
at this point, redundant with: https://github.com/AllenNeuralDynamics/aind-physio-arch/issues/252
and I close.
